language: php

php:
  - 5.4
  - 5.5
  - 5.6


sudo: false

before_install:
  - composer self-update

install:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --bootstrap vendor/autoload.php test

